apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinto
  namespace: weihnachtsmarkt
  labels:
    app: kinto
spec:
  selector:
    matchLabels:
      app: kinto
  template:
    metadata:
      labels:
        app: kinto
    spec:
      containers:
      - name: kinto
        image: kinto/kinto-server:10.1.2
        ports:
        - name: api
          containerPort: 8888
        # env:
        #     args: ["-db=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgis?sslmode=disable", "mosmix_l"]
        # kinto.storage_url = postgres://postgres:postgres@localhost/postgres
        env:
        - name: KINTO_STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: kinto
              key: kinto.storage_url
        volumeMounts:
        - name: config
          mountPath: /etc/kinto
      volumes:
      - name: config
        configMap:
          name: kinto
