apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinto
  namespace: weihnachtsmarkt
  labels:
    app: kinto
spec:
  selector:
    matchLabels:
      app: kinto
  template:
    metadata:
      labels:
        app: kinto
    spec:
      containers:
      - name: kinto
        # image: kinto/kinto-server:10.1.2
        image: kinto/kinto-server:latest
        ports:
        - name: api
          containerPort: 8888
        env:
        - name: KINTO_STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: kinto
              key: kinto.storage_url
        - name: KINTO_PERMISSION_URL
          valueFrom:
            secretKeyRef:
              name: kinto
              key: kinto.permission_url
        volumeMounts:
        - name: config
          mountPath: /etc/kinto
      volumes:
      - name: config
        configMap:
          name: kinto
