apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: weihnachtsmarkt
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.5-alpine
        ports:
        - name: postgres
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
          subPath: mount
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres
