apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: weihnachtsmarkt
  labels:
    app: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgres
