apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: weihnachtsmarkt
spec:
  storageClassName: local-ssd-normal-resilience
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
